### ISSUE TITLE
Application doesn't launch on Windows 10

### ISSUE THREAD

**Issue by clicurt** [roblatour/Push2Run#2] opened 2024-12-15 00:34 UTC
After installation, when the application is launched it doesn't show up.

**Comment by roblatour** [comment] 2024-12-15 00:38
is it in your systray?   If yes, what happens if you left click on the icon in your systray and then click on Main Window?

**Comment by clicurt** [comment] 2024-12-15 00:44
Hello Rob,

The app is not in the system tray. It is not even in the list of running
processes in the task manager.

Thanks for the swift reply.

Curt.

**Comment by roblatour** [comment] 2024-12-15 00:46
ok - I'll need to fire up a w10 machine, will take a look at this as soon as i can

**Comment by clicurt** [comment] 2024-12-15 01:30
Thanks,
I'll try that and let you know how it goes.

**Comment by roblatour** [comment] 2024-12-18 22:32
Hi @clicurt , were you able to try out Push2Run after installing the dot net framework?

**Comment by roblatour** [comment] 2024-12-21 01:06
As an update on this issue, I also dug up an old W10 (physical) computer, applied all Microsoft W10 updates to it, and tried Push2Run - and Push2Run worked just fine on it too.

**Comment by clicurt** [comment] 2024-12-21 03:44
Hello Rob,

Unfortunately, that didn't solve the issue either.
I installed it in my virtual machine on Windows 10 and it worked perfectly.
I guess there is something on my machine blocking the app from starting. I
added Push2run to allowed programs in Windows Defender but that didn't help
either.
I also tried running it in various compatibility modes to no avail.
I will let you know if I succeed in resolving this issue.
I noticed others are facing the same issue during my google search.


Best Regards,
Curtis.

**Comment by roblatour** [comment] 2024-12-21 04:04
Thanks Curtis, I didn't know others were having this problem too.

Are you at all familiar with Visual Studio? If yes, as the source is available you should be able to run it in debug mode on your W10 machine and see if you can find where it is erroring out.   I would do it myself, but it it is working fine on both my W10 machines (one virtual and one physical) and can't recreate the problem.  If your not familiar with Visual Studio then no worries I will leave this issue open.

**Comment by clicurt** [comment] 2024-12-21 04:33
I'm familar with Visual Studio. I'll install it and let you know my results later.
Thank you.

**Comment by roblatour** [comment] 2024-12-21 11:55
I just struck me, as I was waking up this morning, is the W10 machine that you are having troubles with running the 32 bit version of Windows?

**Comment by clicurt** [comment] 2024-12-21 12:47
No, it's running a 64bit Windows 10 professional. Actually I was using
Push2Run on the same machine for more than 3 years I think B4 everything
was moved to GitHub. It was working without issues then even after several
updates.

**Comment by roblatour** [comment] 2024-12-21 13:27
ok

Here is the a copy of the installer for version 4.8.3 - which is the version released prior to going to github:

https://6ec1f0a2f74d4d0c2019-591364a760543a57f40bab2c37672676.ssl.cf5.rackcdn.com/Push2RunSetupv483.exe

Changes in the code were quite minor in the 4.9 release, an additional display in the session log about dropbox (if the folders it should be using are missing), and some links were changed from the push2run.com website to point to github instead.  However, I did also remove the obfuscation (which should not impact anything) + bumped some components to their most current version - which may be the cause of this problem.

Perhaps you can manually uninstall the version of Push2Run on your W10 machine and try installing from the setup program linked above.  Would be curious to know if it starts with the prior version.

Another thing I'm thinking it could be is that somehow your settings / database file got corrupted - but I would think that is more of a long shot.

Rob

**Comment by clicurt** [comment] 2024-12-22 01:12
I ran the debug and got some exceptions but then I can't really make sense of it since.
Below is the debug log:


![image](https://github.com/user-attachments/assets/88348601-447d-448c-9222-abaee5975b21)
![image](https://github.com/user-attachments/assets/2da07368-b630-4dd7-b6a0-923de704b824)


```
'Push2Run.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'D:\projects\.net\Push2Run\Push2Run\bin\Debug\Push2Run.exe'. Symbols loaded.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Remote Debugger\x86\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Desktop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'Push2Run.Application..ctor'
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'Push2Run.Application.InitializeComponent'
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'D:\projects\.net\Push2Run\Push2Run\bin\Debug\MQTTnet.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Push2Run.exe' (CLR v4.0.30319: Push2Run.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.Configuration.ConfigurationErrorsException' in System.Configuration.dll
An exception of type 'System.Configuration.ConfigurationErrorsException' occurred in System.Configuration.dll but was not handled in user code
'.', hexadecimal value 0x00, is an invalid character. Line 15, position 1.

The thread 31752 has exited with code 0 (0x0).
The thread 15392 has exited with code 0 (0x0).
An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll
'The invocation of the constructor on type 'Push2Run.WindowBoss' that matches the specified binding constraints threw an exception.' Line number '6' and line position '5'.

Extracted embedded document 'System.Windows.Markup\WpfXamlLoader.cs' to 'C:\Users\camoy\AppData\Local\Temp\.vsdbgsrc\41f3991a1e606c4091a1ec834297b3119e76e073aa13ccfd04a06d41f346efbd\WpfXamlLoader.cs'

Unhandled Exception: System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'Push2Run.WindowBoss' that matches the specified binding constraints threw an exception.' Line number '6' and line position '5'. ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1. (C:\Users\camoy\AppData\Local\Rob_Latour\Push2Run.exe_StrongName_s42jwjc3kcwndf0tsf1gyjic3sepo3t4\4.8.2.0\user.config line 15) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 15, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   at System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   at System.Configuration.ClientSettingsStore.ReadSettingsFromFile(String configFileName, String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetSettingValuesFromFile(String configFileName, String sectionName, Boolean userScoped, SettingsPropertyCollection properties)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at Push2Run.WindowBoss..ctor() in D:\projects\.net\Push2Run\Push2Run\WindowBoss.xaml.vb:line 137
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at Push2Run.Application.Main()
The program '[93648] Push2Run.exe' has exited with code 0 (0x0).

```

**Comment by roblatour** [comment] 2024-12-22 01:23
It is pointing to a problem with your settings file.
However, its pointing to the old settings file for version 4.8.2
C:\Users\camoy\AppData\Local\Rob_Latour\Push2Run.exe_StrongName_s42jwjc3kcwndf0tsf1gyjic3sepo3t4\4.8.2.0\user.config

can you please go to 
C:\Users\camoy\AppData\Local\Rob_Latour\Push2Run.exe_StrongName_s42jwjc3kcwndf0tsf1gyjic3sepo3t4\4.8.2.0
and open the file 
user.config
with something like Notepad++ to look at it.
I'm thinking there may be something wrong with it.

Also, Push2Run would have automatically made some back up of it.
Please take a look at the Read me.txt file in the same directory - it will give you some instructions on how to fix things up.

Also, please look into:
C:\Users\camoy\AppData\Local\Rob_Latour\Push2Run.exe_StrongName_s42jwjc3kcwndf0tsf1gyjic3sepo3t4\4.9.0.0
what is in there.

What happens if you correct the contents of 
C:\Users\camoy\AppData\Local\Rob_Latour\Push2Run.exe_StrongName_s42jwjc3kcwndf0tsf1gyjic3sepo3t4\4.8.2.0
and delete the contents of 
C:\Users\camoy\AppData\Local\Rob_Latour\Push2Run.exe_StrongName_s42jwjc3kcwndf0tsf1gyjic3sepo3t4\4.9.0.0

and start the Push2Run 4.9.0.0 again

**Comment by clicurt** [comment] 2024-12-22 01:27
Yes. I got the same solution from chatGPT and I deleted the user files and it's running now.

**Comment by clicurt** [comment] 2024-12-22 01:28
I will use the settings from my previous version since Push2Run was running without issues with those settings.

**Comment by roblatour** [comment] 2024-12-22 02:10
ok - so is it version 4.9 that is working for you now?

**Comment by clicurt** [comment] 2024-12-22 03:17
I think I'm running version 4.8. I'll verify and get back to you when I get
back home.

**Comment by clicurt** [comment] 2024-12-22 03:35
I'm using version 4.9

**Comment by clicurt** [comment] 2024-12-22 05:05
Sometimes I get the following error after publishing mqtt message and then Push2Run freezes:

![image](https://github.com/user-attachments/assets/85b50d06-0184-4bb7-a2f5-42e2786646de)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '-1' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.GetItemState(Int32 index, Int32 mask)
   at System.Windows.Forms.ListViewItem.get_StateImageIndex()
   at System.Windows.Forms.ListView.ListViewNativeItemCollection.Add(ListViewItem value)
   at System.Windows.Forms.ListView.ListViewItemCollection.Add(ListViewItem value)
   at Microsoft.Windows.ManagementUI.CombinedControls.EventHomeControl.UpdateLogSummaryUI()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9290.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Microsoft.ManagementConsole
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.19041.1
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.ManagementConsole/3.0.0.0__31bf3856ad364e35/Microsoft.ManagementConsole.dll
----------------------------------------
MMCFxCommon
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.19041.1
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/MMCFxCommon/3.0.0.0__31bf3856ad364e35/MMCFxCommon.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9282.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
EventViewer
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.19041.1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/EventViewer/v4.0_10.0.0.0__31bf3856ad364e35/EventViewer.dll
----------------------------------------
MIGUIControls
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.19041.3636
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/MIGUIControls/v4.0_1.0.0.0__31bf3856ad364e35/MIGUIControls.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by roblatour** [comment] 2024-12-22 14:28
Well glad we got the W10 current version of Push2Run not starting for you issue resolved.

But, let's look at this new issue too.

I assume it is on your W10 machine as well.

The error messages aren't helpful as they seem to be in the .net framework itself.

You say you 'sometimes' get this.  Is there anything in particular that may be in common when you do get these?   For example, a particular  Push2Run window is open, a particular mqtt message is received?

Were you getting this with the prior version of the program?

**Comment by FelipeMarnai** [comment] 2024-12-23 23:52
work in another lenguages? exemple portuguese ?

**Comment by roblatour** [comment] 2024-12-24 00:03
@FelipeMarnai  
não, o Push2Run está apenas configurado para funcionar com inglês.  
no, Push2Run is only set up to work with English.

**Comment by clicurt** [comment] 2024-12-27 03:36
> Well glad we got the issue of current version of Push2Run not starting on W10 for you resolved.
> 
> But, let's look at this new issue too.
> 
> I assume it is on your W10 machine as well.
> 
> The error messages aren't helpful as they seem to be in the .net framework itself.
> 
> You say you 'sometimes' get this. Is there anything in particular that may be in common when you do get these? For example, a particular Push2Run window is open, a particular mqtt message is received?
> 
> Were you getting this with the prior version of the program?

Sorry,
It's been a busy week for me. 
I can't really say what caused it or whether it was the same with the previous versions of P2R. 
I will play around with it a little more and open an issue when I figure out the cause.

Thank you!

**Comment by roblatour** [comment] 2024-12-27 03:39
ok - best of luck - I'll close this issue for now, as its likely best to address one issue per issue anyway.

Cheers

**Comment by roblatour** [comment] 2024-12-27 03:39
closed as original issue was resolved.

**Closed by roblatour** 2024-12-27 03:39 UTC
